apiVersion: batch/v1
kind: Job
metadata:
  name: {{ include "frkr.fullname" . }}-migrations
  labels:
    {{- include "frkr.labels" . | nindent 4 }}
  annotations:
    "helm.sh/hook": post-install,post-upgrade
    "helm.sh/hook-weight": "1"
    "helm.sh/hook-delete-policy": before-hook-creation,hook-succeeded
spec:
  template:
    metadata:
      labels:
        {{- include "frkr.labels" . | nindent 8 }}
    spec:
      restartPolicy: OnFailure
      containers:
      - name: migrate
        image: postgres:15-alpine
        command: ["sh", "-c"]
        args:
        - |
          echo "Applying migrations..."
          for f in /migrations/*.sql; do
            echo "Applying $f..."
            psql "{{ if .Values.infra }}{{ .Values.infra.databaseURL | default "postgres://root@frkr-cockroachdb:26257/frkrdb?sslmode=disable" }}{{ else }}postgres://root@frkr-cockroachdb:26257/frkrdb?sslmode=disable{{ end }}" -f "$f"
          done
        volumeMounts:
        - name: migrations
          mountPath: /migrations
      volumes:
      - name: migrations
        configMap:
          name: {{ include "frkr.fullname" . }}-migrations
