{{- $pg := .Values.infrastructure.postgres }}
{{- $crdb := .Values.infrastructure.cockroachdb }}
{{- if or $pg.provision $crdb.provision }}
apiVersion: v1
kind: Secret
metadata:
  name: frkr-db-secret
  labels:
    app.kubernetes.io/name: frkr
    app.kubernetes.io/instance: {{ .Release.Name }}
type: Opaque
stringData:
  # Infrastructure password
  {{- if $pg.provision }}
  password: "{{ required "A valid .Values.infrastructure.db.password entry required!" .Values.infrastructure.db.password }}"
  {{- else }}
  password: ""
  {{- end }}
{{- end }}
