apiVersion: frkr.io/v1
kind: FrkrInit
metadata:
  name: frkr-init
  namespace: {{ .Release.Namespace }}
spec:
  databaseUrl: {{ .Values.init.databaseUrl | default (printf "postgres://%s:%s@%s:%v/%s?sslmode=%s" .Values.dataPlane.db.user .Values.dataPlane.db.password .Values.dataPlane.db.host .Values.dataPlane.db.port .Values.dataPlane.db.database .Values.dataPlane.db.sslMode) | quote }}
  gateways:
    - "{{ include "frkr.fullname" . }}-ingest-gateway"
    - "{{ include "frkr.fullname" . }}-streaming-gateway"
