apiVersion: v1
kind: Secret
metadata:
  name: frkr-db-secret
  labels:
    app.kubernetes.io/name: frkr
    app.kubernetes.io/instance: {{ .Release.Name }}
{{- if .Values.infrastructure.postgres.provision }}
type: Opaque
stringData:
  # Infrastructure password
  password: "{{ .Values.infrastructure.postgres.env.postgresPassword | default "password" }}"
{{- end }}
